-- 코드를 입력하세요
SELECT ii.INGREDIENT_TYPE
     , SUM(TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF fh
  JOIN ICECREAM_INFO ii
    ON fh.FLAVOR = ii.FLAVOR
 GROUP BY ii.INGREDIENT_TYPE
 ORDER BY TOTAL_ORDER